# Data Schema for Credit Card Fraud Detection
columns:
  merchant: string
  category: string
  amt: float64
  gender: string
  street: string
  city: string
  state: string
  zip: string
  lat: float64
  long: float64
  city_pop: int64
  job: string
  dob: string
  trans_num: string
  merch_lat: float64
  merch_long: float64
  is_fraud: int64
  hour: int64
  day: int64
  month: int64
  year: int64
  is_night: int64
  age: int64

target_column: is_fraud
